---
name: Lint Code
description: Run eslint and prettier --check

on:  # yamllint disable-line rule:truthy
  push:
    paths:
      - src/**

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4

      - name: Install npm dependencies
        run: npm ci --include=dev

      - name: Run npm run lint
        run: npm run lint
